// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/f305105c139273a1d79048dcfce618ab75172cc7/sleep/sleep.d.ts
declare namespace __node_sleep
{
	/**
	 * Sleep for <i>n</i> seconds.
	 * 
	 * @param n Number of seconds to sleep.
	 */
	function sleep(n: number): void;

	/**
	 * Sleep for n microseconds.
	 * 
	 * @param n Number of microseconds to sleep; 1 second is 1,000,000 microseconds.
	 */
	function usleep(n: number): void;
}

declare module "sleep"
{
	export = __node_sleep;
}
